# Generated by Django 6.0.2 on 2026-03-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stocks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=20)),
                ("price", models.FloatField()),
                ("sector", models.CharField(default="Unknown", max_length=100)),
                ("market_cap", models.BigIntegerField(default=0)),
                ("high_price", models.FloatField(default=0)),
                ("low_price", models.FloatField(default=0)),
                ("pe_ratio", models.FloatField(default=0)),
                ("discount_pct", models.FloatField(default=0)),
                (
                    "opportunity_level",
                    models.CharField(default="Low Opportunity", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_name", models.CharField(max_length=100)),
                (
                    "staff",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="Staff.staff",
                    ),
                ),
                (
                    "stocks",
                    models.ManyToManyField(
                        related_name="portfolios", to="Portfolio.stocks"
                    ),
                ),
            ],
        ),
    ]
