# Generated by Django 6.0.2 on 2026-03-03 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="stocks",
        ),
        migrations.AddField(
            model_name="stocks",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="Portfolio.portfolio",
            ),
        ),
    ]
