# Generated by Django 6.0.2 on 2026-02-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0002_remove_portfolio_stock_portfolio_stocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="market_cap",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stocks",
            name="sector",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
        ),
    ]
