# Generated by Django 6.0.2 on 2026-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0002_remove_portfolio_stocks_stocks_portfolio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocks",
            name="portfolio",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="stocks",
            field=models.ManyToManyField(
                related_name="portfolios", to="Portfolio.stocks"
            ),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="symbol",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
