# Generated by Django 6.0.3 on 2026-03-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0003_remove_stocks_portfolio_portfolio_stocks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="stocks",
        ),
        migrations.AddField(
            model_name="stocks",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="Portfolio.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="symbol",
            field=models.CharField(max_length=20),
        ),
    ]
