# Generated by Django 6.0.2 on 2026-02-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0003_stocks_market_cap_stocks_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="discount_pct",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stocks",
            name="high_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stocks",
            name="low_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="stocks",
            name="opportunity_level",
            field=models.CharField(default="Low Opportunity", max_length=50),
        ),
        migrations.AddField(
            model_name="stocks",
            name="pe_ratio",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="sector",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
