# Generated by Django 6.0.2 on 2026-03-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0004_remove_portfolio_stocks_stocks_portfolio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="historical_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="stocks",
            name="prediction_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
