# Generated by Django 6.0.2 on 2026-02-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_stocks_discount_pct_stocks_high_price_and_more'),
        ('Staff', '0002_alter_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='Staff.staff'),
        ),
    ]
