# Generated by Django 6.0.2 on 2026-03-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0005_stocks_historical_data_stocks_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocks",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
    ]
