# Generated by Django 6.0.2 on 2026-02-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
